### ISSUE TITLE
Support for DOCTYPE?

### ISSUE THREAD

**Issue by murtuzasyed** [punkave/sanitize-html#222] opened 2018-05-08 16:45 UTC
I want to use sanitize-html to sanitize a whole html document rather than a fragment, but currently DOCTYPE is being removed as well. Is there any support or recommendation for DOCTYPE?

**Comment by boutell** [comment] 2018-05-09 13:11
Duplicate of #131

**Closed by boutell** 2018-05-09 13:11 UTC
